# If set to false, the plugin will not allow players to wear a hat if they already have a helmet
# If set to true, hats will be automatically applied, and helmets will be automatically removed
force-remove-helmets: false

# Accepts "MySQL" or "SQL"
storage-method: SQL
# Only configure this section if you are using MySQL
mysql:
  host: example.com
  port: 3306
  user: bukkit
  password: "password"
  database: mysql
  
# A list of worlds where players won't have hats. Case sensitive!
disabled-worlds:
  - example

mainGUI:
  # Title of the gui
  title: "&b&lHats"
  # Size of the GUI - must be a multiple of 9.
  # Remember to change all other slot values below
  # after changing this to prevent errors.
  size: 36
  # How many spaces in the GUI should the hats occupy?
  # Must be less than "size" above.
  # If you change the size, a good idea would be to
  # set this to size - 9
  hatsSize: 27
  # Fill the unused slots in the GUI with an item
  fill:
    enabled: true
    item: BLUE_STAINED_GLASS_PANE
    name: ""
    # The starting and ending slots; all items in between (inclusive)
    # will be filled with the specified item.
    # Slots are 0-indexed, i.e. slot 1 is 0
    start: 27
    end: 35 
  # The button to unequip current hat
  unequip:
    item: BARRIER
    name: "&dUnequip current hat"
    lore:
      - ""
      - "&7Click to unequip your current hat,"
      - "&7if you are wearing any."
    slot: 32
  # Page buttons, should there be multiple pages
  next-page:
    item: ARROW
    name: "&fNext page"
    slot: 35
  last-page:
    item: ARROW
    name: "&fLast page"
    slot: 27
  # Extra, non-hat items can be added as required. They can execute commands, 
  # using variable %player% if needed. You MUST include a "slot" option for each item
  extra-items:
    example-back-button:
      item: RED_STAINED_GLASS_PANE
      name: "&cBack"
      slot: 31
      commands:
        - "bossshop open cosmetics %player%"
      
# Messages sent by plugin to player
strings:
  prefix: "&b&lHats &8&l» &7"
  hat-selected: "You are now wearing the %hat% &7hat"
  hat-unequipped: "You unequipped your hat."
  armor-equipped: "&cYou are already wearing another item!"
  armor-removed: "&eThe item you were previously wearing was placed in your inventory or dropped."
  requirements-not-met: "&cYou don't own this hat!"
  not-enough-money: "&cYou don't have enough money for this purchase!"
  hat-purchased: "You bought %hat% &7for &a%cost%&7!"
  
# Sounds associated to messages
sounds:
  hat-selected:
    sound: ITEM_ARMOR_EQUIP_IRON
    volume: 1.0
    pitch: 1.0
  hat-unequipped:
    sound: ITEM_ARMOR_EQUIP_ELYTRA
    volume: 1.0
    pitch: 1.0
  hat-purchased:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.0
  requirements-not-met:
    sound: BLOCK_NOTE_BLOCK_BASS
    volume: 1.0
    pitch: 1.0
  not-enough-money:
    sound: BLOCK_NOTE_BLOCK_BASS
    volume: 1.0
    pitch: 1.0
  
# Lore added to the end of hats to indicate locked status
lore:
  locked:
    - ""
    - "&cLocked"
  unlocked:
    - ""
    - "&eClick to select!"
  selected:
    - ""
    - "&aSelected!"
  buyable:
    - ""
    - "&eAll requirements met!"
    - "&6Cost: &b$%cost%"
 