# If set to false, the plugin will not allow players to wear a hat if they already have a helmet
# If set to true, hats will be automatically applied, and helmets will be automatically removed
force-remove-helmets: false

# Accepts "MySQL" or "SQL"
storage-method: SQL
# Only configure this section if you are using MySQL
mysql:
  host: example.com
  port: 3306
  user: bukkit
  password: "password"
  database: mysql
  
# A list of worlds where players won't have hats. Case sensitive!
disabled-worlds:
  - example

mainGUI:
  # Size of the GUI - must be a multiple of 9.
  size: 36
  # Fill the unused slots in the GUI with an item
  fill:
    enabled: true
    item: BLUE_STAINED_GLASS_PANE
    name: ""
    # The starting and ending slots; all items in between (inclusive)
    # will be filled with the specified item.
    # Slots are 0-indexed, i.e. slot 1 is 0
    start: 27
    end: 35 
  # New, non-hat items can be added as required. They can execute commands, 
  # using variable %player% if needed.
  example-back-button:
    item: RED_STAINED_GLASS_PANE
    name: "&cBack"
    slot: 31
    commands:
      - "bossshop open cosmetics %player%"