name: UltimaHats
version: 1.0.0
main: com.leomelonseeds.ultimahats.UltimaHats
api-version: 1.19
author: M310N
description: A feature-rich Hats cosmetic Spigot plugin.
softdepend:
  - Vault
  - PlaceholderAPI
commands:
  ultimahats:
    description: The core UltimaHats command
    aliases:
      - hats
      - hat
permissions:
  ultimahats.hats:
    default: true
  ultimahats.reload: {}
  ultimahats.currentitem: {}
  ultimahats.apply: {}
  ultimahats.remove: {}
  
